apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    path: argocd/
    repoURL: https://github.com/benjaminBoboul/gitops-infrastructure.git
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc