apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yml
  - argo-cd/manifests/install.yaml
  - gitops-repo.yml
patches:
  - argo-cd-repo-server-ksops-patch.yml
  - argo-cd-allow-alpha-plugins-patch.yml
  - argo-cd-import-pgp-key.yml
generators:
  - secret-generator.yml